### ISSUE TITLE
Port CCop overcommit hook to OS X

### ISSUE THREAD

**Issue by sethk** [deivid-rodriguez/byebug#228]
This is super low priority, but it would be nice if I could use your ‘CCop’ hook. It requires these config changes:

```
PreCommit:
  CCop:
    required_executable: gindent
    install_command: brew install gnu-indent
```

Notice the lack of ``sudo`` before ``brew``, typically ``sudo`` is not needed there.

Now the question is: is there a way to special-case the YAML for OS X vs. Linux?

Additional gory detail:

Darwin/BSD has its own version of indent(1), but it doesn't support the longer configuration switches. It's possible it could be made to work with the short options (such as ``-bad``), but that's obviously less readable.
